### PR TITLE
run cleanupRelay only once in TerminalIO and StandardIO

### LINKED ISSUE #124: [Bug]: The CI has a high failure rate
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

1. Trigger PR checks.

### Current behavior

There is a high chance of getting this:
```
2025-06-13T23:58:46+0000 error com.apple.containerization : [containerization_integration] ❌ test multiple concurrent processes with output stress failed: internal error (13): startProcess: failed to start process: Error Domain=NSPOSIXErrorDomain Code=9 "Bad file descriptor"
2025-06-13T23:58:46+0000 info com.apple.containerization : [containerization_integration] 
Integration suite completed in 19.997790932655334s with 8/10 passed and 1/10 skipped!
2025-06-13T23:58:46+0000 error com.apple.containerization : [containerization_integration] ❌
```

### Expected Behavior

The tests pass.

### Environment

```markdown
Reproducible in CI only.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by elijah-wright**
possibly fixes #124

### CODE REVIEW

**Comment by elijah-wright** [comment]
@adityaramani I think the formatting issues have been fixed

**Comment by adityaramani** [comment]
Im gonna pull in the changes locally and test it out as well

**Comment by elijah-wright** [comment]
thank you, I've been depending on the workflow tests and it's not fair to you that they're not passing

**Comment by adityaramani** [comment]
No worries at all!

**Comment by adityaramani** [comment]
Tried running the tests in a loop and it failed with this, and there werent any other logs from the guest
```
2025-06-18T14:50:23-0700 error com.apple.containerization : [containerization_integration] ❌ test multiple concurrent processes with output stress failed: internalError: "failed to start process" (cause: "internal error (13): startProcess: failed to start process: Error Domain=NSCocoaErrorDomain Code=256 "(null)"UserInfo={NSUnderlyingError=Error Domain=NSPOSIXErrorDomain Code=9 "Bad file descriptor"}")
```

I'll try combining your change with what I was testing out with the `writeFd` being deinited

File: vminitd/Sources/vminitd/StandardIO.swift [hunk 1]
```diff
@@ -119,6 +119,10 @@ final class StandardIO: ManagedProcess.IO & Sendable {
         }
     }
 
+    final class RelayState: @unchecked Sendable {
```
Comment (dcantah) [inline vminitd/Sources/vminitd/StandardIO.swift]: I wonder, can this be a struct?

Comment (dcantah) [reply vminitd/Sources/vminitd/StandardIO.swift]: Well truthfully, although the Swift gods will scorn us, we know with the current implementation that the epoll callback should never run concurrently, so we could likely use an inline bool in StandardIO and TerminalIO. You'll probably have to mark it as nonisolated(unsafe) however

Comment (dcantah) [reply vminitd/Sources/vminitd/StandardIO.swift]: The same scheme we use for the buffers for both the relays

**Comment by elijah-wright** [comment]
dang, I really thought that was going to solve it. I'm going to look at this again when I get home, I got caught in a literal sandpit 💀

File: vminitd/Sources/vminitd/StandardIO.swift (hunk 1 above)
Comment (adityaramani) [reply vminitd/Sources/vminitd/StandardIO.swift]: I think we can use the `@SendableProperty` macro we have and define a boolean
```
    @SendableProperty
    private var closed: Bool = false
...

    func cleanupRelay(...) {
        guard !self.closed else {
            return
        }
        ...
```

Comment (dcantah) [reply vminitd/Sources/vminitd/StandardIO.swift]: That also works, I just don't think we actually need to lock here today. But realistically this would be completely negligible 🐸, and if we ever changed the behavior of the epoll callbacks `SendableProperty` is probably the better option, but I'd hope if the behavior changed we'd make that configurable in the api itself

Comment (elijah-wright) [reply vminitd/Sources/vminitd/StandardIO.swift]: > I wonder, can this be a struct? 

I created this as a class with a function before I realized that it didn't need to be a function but I didn't change its type

and yeah I did look at `NSLock` but I figured it was ok not to use it since this isn't multithreaded

Comment (dcantah) [reply vminitd/Sources/vminitd/StandardIO.swift]: >and yeah I did look at NSLock but I figured it was ok not to use it since this isn't multithreaded

I also think it's fine given the epoll implementation we have. Wanna trial the inline bool idea?

Comment (elijah-wright) [reply vminitd/Sources/vminitd/StandardIO.swift]: ok I did 👍

File: vminitd/Sources/vminitd/StandardIO.swift [hunk 2]
```diff
@@ -128,9 +128,16 @@ final class StandardIO: ManagedProcess.IO & Sendable {
         // `buf` isn't used concurrently.
         nonisolated(unsafe) let buf = UnsafeMutableBufferPointer<UInt8>.allocate(capacity: Int(getpagesize()))
 
+        nonisolated(unsafe) var didCleanup = false
```
Comment (dkovba) [inline vminitd/Sources/vminitd/StandardIO.swift:131]: Is `didCleanup` thread-safe? Should we access it within a lock? The same applies to `TerminalIO.swift`.

Comment (elijah-wright) [reply vminitd/Sources/vminitd/StandardIO.swift:131]: I think @dcantah and I talked about this, it should be fine to use an inline bool here since there's no multithreading

**Comment by adityaramani** [comment]
Thanks! I think your changes look good - and I tested it after adding in a couple of other fixes (see here https://github.com/adityaramani/containerization/tree/vminitd-crash) 

Although I do think there maybe some other issues in the process handling flow,  this change makes it more stable.

Will wait for the others to review

File: vminitd/Sources/vminitd/StandardIO.swift (hunk 2 above)
Comment (dkovba) [reply vminitd/Sources/vminitd/StandardIO.swift:131]: It might be worth adding `didCleanup` into the comment about thread-safety of `buf`.

Comment (elijah-wright) [reply vminitd/Sources/vminitd/StandardIO.swift:131]: I did 👍

**Comment by elijah-wright** [comment]
@adityaramani do you want me to cherry pick your commit? it's only partially signed so I don't know

**Comment by adityaramani** [comment]
Yeah go for it. Take that commit in. If the signature are a problem just apply the diff

**Comment by elijah-wright** [comment]
ok done, but it says unverified

**Comment by adityaramani** [comment]
Yeah. Maybe try removing me as author?

**Comment by elijah-wright** [comment]
@adityaramani if I could ask, what are the specs of the machine you're testing on?

**Comment by adityaramani** [comment]
It's an M2 Pro with 64 gb of ram. Are you asking cause you don't see the issue on your end?

I need to run the test on a loop and see it failing once in like 15 times

**Comment by elijah-wright** [comment]
I was just wondering, I think it has to be a race condition then. increasing system load (`stress-ng`) might make it more predictable for testing if that's true

File: vminitd/Sources/vminitd/ProcessSupervisor.swift [hunk 3]
```diff
@@ -64,10 +64,15 @@ actor ProcessSupervisor {
         let exited = Reaper.reap()
         self.log?.debug("finished wait4 of \(exited.count) processes")
 
-        for proc in processes {
-            let pid = proc.pid
-            self.log?.debug("checking for exit of managed process", metadata: ["pid": "\(pid)", "exits": "\(exited)"])
+        self.log?.debug("checking for exit of managed process", metadata: ["exits": "\(exited)", "processes": "\(processes.count)"])
```
Comment (dcantah) [inline vminitd/Sources/vminitd/ProcessSupervisor.swift:67]: Great catch 😆

**Review by dcantah — APPROVED** [review]
This looks good to me, but I'll wait for either @adityaramani or @crosbymichael to give it a second thumbs up.

**Comment by adityaramani** [comment]
LGTM! I think Michael should take a look as well
