### PR TITLE
vminitd: Proper pty setup / mount /dev/console

### LINKED ISSUE #145: [Bug]: Need to set up /dev/console
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

We don't set up /dev/console today in containers as a bind mount to the currently opened pty.

### Current behavior

Asking for terminal=true should cause our pal /dev/console to appear.

### Expected Behavior

/dev/console to exist after asking for a terminal.

### Environment

```markdown
- OS: 26 beta
- Swift: 6.2
- Xcode: 26 beta
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #246: [Bug]: A race condition in the `IOPair` class
### I have done the following

- [x] I have searched the existing issues
- [ ] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

The race condition occurs when:

1. Thread A is executing the `relay()` method, actively reading/writing using `self.buffer`.
2. Thread B calls the `close()` method, which calls `self.buffer.deallocate()`.

### Current behavior

Thread A tries to access the deallocated `self.buffer` in thread B, leading to a crash.

### Expected behavior

Access to `self.buffer` should be thread-safe.

### Environment

```markdown
N/A
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dcantah**
Closes #246 
Closes #145

We need to allocate the pty in the containers ns otherwise you run into funny outcomes later. This change additionally mounts /dev/console by binding the pty opened in the containers namespace onto it. Today /dev/console is solely from devtmpfs which points at /dev/hvc0, or the virtio serial console. This causes systemds output to go to serial/the bootlog
instead of what folks would expect. This should make systemd like us a lot more than it does today.

Another large change that was somewhat required here is the changes in IOPair. EPOLLHUP on a pty is deceptively weird to handle as it could be reopened, so we can't do what we were doing today and just close all the fds. To remedy this I skip exiting on HUP for pty's and instead just cleanup at process exit time, but ensure to drain the pty beforehand.

### CODE REVIEW

**Comment by dcantah** [comment]
@elijah-wright I can't add you as a reviewer, but I'd still like your feedback on this :)

**Comment by dcantah** [comment]
Will fix the merge conf after that last check in

**Comment by elijah-wright** [comment]
ok I'll look at this right now

File: vminitd/Sources/vmexec/Console.swift [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+            throw App.Errno(stage: "ptsname")
+        }
+
+        self.master = masterFD
+        self.slavePath = String(cString: slavePath)
+    }
+
+    func configureStdIO() throws {
+        let path = self.slavePath
+        let slaveFD = open(path, O_RDWR)
```
Comment (elijah-wright) [inline vminitd/Sources/vmexec/Console.swift:44]: is `slaveFD` closed anywhere? I think it's open until `execve`

File: vminitd/Sources/vmexec/RunCommand.swift [hunk 2]
```diff
@@ -49,92 +49,124 @@ struct RunCommand: ParsableCommand {
...
 
-            // Apply O_CLOEXEC to all file descriptors except stdio.
-            // This ensures that all unwanted fds we may have accidentally
-            // inherited are marked close-on-exec so they stay out of the
-            // container.
-            try App.applyCloseExecOnFDs()
+            try mountConsole(
+                path: pty.slavePath,
+                uid: process.user.uid,
+                gid: process.user.gid
```
Comment (elijah-wright) [inline vminitd/Sources/vmexec/RunCommand.swift]: shouldn't this match the default GID of 5 for `tty`?

File: vminitd/Sources/vmexec/Console.swift (hunk 1 above)
Comment (dcantah) [reply vminitd/Sources/vmexec/Console.swift:44]: No, great catch!

File: vminitd/Sources/vmexec/RunCommand.swift (hunk 2 above)
Comment (dcantah) [reply vminitd/Sources/vmexec/RunCommand.swift]: Another great catch, the chown was a leftover it seems

File: vminitd/Sources/vmexec/Console.swift (hunk 1 above)
Comment (dcantah) [reply vminitd/Sources/vmexec/Console.swift:44]: We will set it as cloexec shortly below however, but better to just close it right away for clarity.

**Review by dkovba — COMMENTED** [review]
👍 This should resolve https://github.com/apple/containerization/issues/246.

**Comment by dcantah** [comment]
Going to draft this, as execs seem to have a hang when asking for a pty that isn't seen for the init proc

**Comment by elijah-wright** [comment]
oh I think I was doing some work in that area this afternoon. I'm at work rn but I can look at that in a few hours

**Comment by dcantah** [comment]
Ok, execs fixed. It was just a pipe I wasn't closing.
