### PR TITLE
LinuxContainer/LinuxPod: Fix UDS proxy if target is symlink

### LINKED ISSUE #256: [Bug]: Can't mount a host socket when the mount target goes through a symlink.
### I have done the following

- [x] I have searched the existing issues
- [ ] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

```console
% ls ${SSH_AUTH_SOCK}
/private/tmp/com.apple.launchd.qylZi0PDA7/Listeners

% container run -it --rm --volume "${SSH_AUTH_SOCK}:/var/run/ssh-auth.sock" --env SSH_AUTH_SOCK=/var/run/ssh-auth.sock ubuntu:latest bash
root@3c3908f9-a1de-4ac5-9f36-6f8bf194dab1:/# ls ${SSH_AUTH_SOCK}
ls: cannot access '/var/run/ssh-auth.sock': No such file or directory
root@3c3908f9-a1de-4ac5-9f36-6f8bf194dab1:/#
```

### Current behavior

Mounted socket is inaccessible.

### Expected behavior

```console
% container run -it --rm --volume "$(realpath ${SSH_AUTH_SOCK}):/run/ssh-auth.sock" --env SSH_AUTH_SOCK=/var/run/ssh-auth.sock ubuntu:latest bash 
root@9a626d00-d1ce-4f03-ae17-6784c07dd8b8:/# ls ${SSH_AUTH_SOCK}
/var/run/ssh-auth.sock
```

The this particular case, `ssh-add -l` should work properly, as should `git clone` via ssh.

### Environment

```markdown
- OS: macOS 26 developer preview
- Swift: Apple Swift version 6.2
- Xcode: Xcode 26 beta
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dcantah**
Closes #256

If the target of the uds proxy goes through a symlink (/var/run) we had the same bug we had with mounts previously where we'd follow this and if the resolved path existed in the root of the VM we'd end up mounting there. Fix this by plopping the sockets in a holding spot and then bind mounting them in (which has the correct resolution logic).

### CODE REVIEW

File: Sources/Containerization/LinuxPod.swift [hunk 1]
```diff
@@ -254,6 +254,10 @@ public final class LinuxPod: Sendable {
     private static func guestRootfsPath(_ containerID: String) -> String {
         "/run/container/\(containerID)/rootfs"
     }
+
+    private static func guestSocketStagingPath(_ containerID: String, socketID: String) -> String {
```
Comment (jglogan) [inline Sources/Containerization/LinuxPod.swift:258]: Not necessary today, but at some point DRY this out by extracting this onto a UnixSocketConfiguration extension? Maybe there's other duplicate code between pod and container that can benefit from this treatment.

Comment (dcantah) [reply Sources/Containerization/LinuxPod.swift:258]: It's likely we could get some benefit for how single files are setup as they're similar
